### ISSUE TITLE
Data type mismatch when running database migrations

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#138]
When running `python manage.py makemigrations` followed by `python manage.py migrate`, I get this error: `django.db.utils.IntegrityError: datatype mismatch`. I cloned a fresh copy and still get the error. This is the exact sequence I did if anyone wants to reproduce it. Anyone know why this is happening, or if it's a problem just on my end?

```
git clone git@github.com:phageParser/phageParser.git phageParsertest
cd phageParsertest/phageAPI
git checkout django-dev
python manage.py makemigrations
python manage.py migrate # this is where the error happens
```

This is the full error message:

```
  Applying restapi.0002_auto_20170413_1317...Traceback (most recent call last):
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: datatype mismatch

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/db/migrations/operations/fields.py", line 204, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 495, in alter_field
    old_db_params, new_db_params, strict)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/db/backends/sqlite3/schema.py", line 255, in _alter_field
    self._remake_table(model, alter_fields=[(old_field, new_field)])
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/db/backends/sqlite3/schema.py", line 199, in _remake_table
    self.quote_name(model._meta.db_table),
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/madeleine/anaconda2/envs/django/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: datatype mismatch
```

**Comment by mbonsma** [comment]
@cemyld, we couldn't figure this one out, but think it has something to do with the previous version of models.py that was migrated first.

**Comment by cemyld** [comment]
@mbonsma I think the problem arises since the models file has been changed and not been migrated to the old database. I would suggest resetting the database first and then migrating. According to [this](http://stackoverflow.com/questions/15454008/how-to-reset-db-in-django-i-get-a-command-reset-not-found-error), resetting can be done by running `python manage.py flush`

**Comment by mbonsma** [comment]
That did the trick! Thanks @cemyld! Should we add this to a doc somewhere or modify the repo version so that it works on initial download?

**Comment by danielliekal** [comment]
Running python manage.py flush as suggested above worked for me.

**Comment by ghost** [comment]
It works for me!
but I have to run```python manage.py createsuperuser``` to create a superuser again.

**Comment by mir4zul** [comment]
@cemyld 

That did the trick! good working my project..thanks a lot

**Comment by mir4zul** [comment]
@cookie-brown

To flush means to makes a new migration
